### PR TITLE
Revamp seats placement and other math

### PR DESCRIPTION
**Pull request by Gouvernathor**
The `TOTALS` list was replaced with a generating function called Totals. It doesn't generate exactly the same numbers, but I believe this is for the better.

Math explaination for its code :
Assuming 1 to be the total width or diameter of the hemicycle, accounting for the thickness of the outer row's seats.
`rad` is the radius of the seats/circles, if they were to touch each of their neighbors without margins (which are ignored for the calculation)
`r` is the number of the row considered (starting from the innermost one)
`R` is the radius of the `r` row, considering it as a circle which would cross the center of each seat in the row
`tot` sums up the maximum number of seats which can fit in each row

I tested the formula in a version of this ported to another render engine, which can be found [here](https://github.com/Gouvernathor/renpy-ParliamentDiagram) and which works perfectly. However, I expect some of the code here will have to be adapted for it to place the seats in an optimized fashion.

This has the side-effect of removing the maximum number of seats a diagram can fit.

### CODE REVIEW

**Comment by Gouvernathor** [comment]
I updated the part of the code which determined the spot of the center of each seat, the get_spots_center function.

Mostly the same math, except for some details :
- the calculation of the number of seats to place in each row (`nb_seats_to_place`) was changed, which follows my changing the Totals values, so no problem there
- I used a 1.0 constant at line 228, you used 1.75. I assume it's to have a supplementary margin above the hemicycle so I kept it 1.75
- You used a sine to calculate the `sin_r_rr` value, while I used an arc-sine in the corresponding parts of my code. I don't understand why, so I kept my version, but this should probably be cleared before merging the PR.

**Comment by Gouvernathor** [comment]
I also removed the "denser rows" option, so it would make sense to remove it from the front-end part of the system.
I'm not sure I'm fluent enough in javascript to do it though.

**Comment by slashme** [comment]
Thank you very much!

I'll check this out on Sunday and either make it live, make suggestions, or hack around and make it live.

**Comment by slashme** [comment]
> I also removed the "denser rows" option, so it would make sense to remove it from the front-end part of the system.
> I'm not sure I'm fluent enough in javascript to do it though.

The "denser rows" option definitely has to stay: it's an enhancement that @Rade-Mathis added to solve spacing issues with small diagrams.

**Comment by Gouvernathor** [comment]
The repartition of seats has changed, now each row (but the last) contains exactly as many seats as it can store, so perhaps that option isn't needed anymore ?
I don't understand what that option changes precisely, since my code was based upon an older version of thus git I couldn't say with certainty if my changes make it obsolete or not. Maybe it would still be an issue for single-row archs ?
If you want I can generate displays for how the smallest newarch order their seats ?

**Comment by Gouvernathor** [comment]
Actually the formula I used for the seats' radius differs from yours.
Ignoring the thickness of the circle's border, you're ending up using `40/nb_rows`, in pixels I guess.
I'm using `.8*.5*a/(4*nb_rows-2)`, `a` being the width of the diagram. It's 80% of their maximal radius, with which they would touch but not overlap each others.
Once converted for this context, with `a` being 350px, It translates to `.8*175/(4*nb_rows-2)`, minus the border tweak.

This change induces an increase in radius for assemblies with fewer seats, so this may by itself solve the issue adressed by the "denser rows" option.

My previous changes in the seats' centers math were false before I changed this, which reminds me that this code in this context should be tested. I'll try to test it in the coming days.

**Comment by slashme** [comment]
The code isn't working for me:

```
  File "newarch.py", line 221, in get_spots_centers
    nb_seats_to_place = int(float(nb_delegates) / self.totals[nb_rows-1] * math.pi*R/(2*spot_radius))
NameError: global name 'self' is not defined
```

Note, the line number isn't quite accurate, because I had to put in three extra lines at the top to grab the list of parties from a local file, instead of getting it via a CGI interface.

**Comment by Gouvernathor** [comment]
Oops. You have to use the `Totals` function instead of `self.totals`.

**Comment by Gouvernathor** [comment]
@slashme bump, in case you don't get notifications since the PR is closed

**Comment by slashme** [comment]
All clear! Will fix it and test again, but not today or tomorrow (day job and other stuff going on ;-D )

**Comment by slashme** [comment]
> @slashme bump, in case you don't get notifications since the PR is closed

Definitely am getting notifications: just sometimes slow to reply.

**Comment by Gouvernathor** [comment]
Ok, np !

**Comment by slashme** [comment]
Hi @Gouvernathor 

I won't be implementing it as it stands, for the following reasons:

* All parliaments under size 12 just lump all the spots in the middle of the diagram  
* As the number of spots increases, they just get closer together in the rows until they all overlap.

See the results of my test: [svgtest.tar.gz](https://github.com/slashme/parliamentdiagram/files/7190502/svgtest.tar.gz)

**Comment by Gouvernathor** [comment]
The code I wrote in renpy (the one I'm trying to retrofit here) works fine and doesn't give those weird stuff at all, so I must have failed the porting in some way. I have a suspicion it's about the Totals stuff which seems to be off by one indice, but I'm not completely sure.

Could you send me the python code which locally creates the svg files, which you seem to have created ? That way I could do the crash-testing myself.

**Comment by slashme** [comment]
Hi @Gouvernathor 

In the branch "Revamp" I added a file called "data" that holds the JSON that defines the diagram to be built, and in newarch.py I've added some code (commented out) that loads the information from any file that's specified on the command line.

After commenting rows 18-20 and uncommenting rows 22-24 you get:

```
 18     #form = cgi.FieldStorage()
 19     #data = form.getvalue("data", "")
 20     #inputlist = json.loads(data)
 21     #Uncomment this to load data from command line
 22     with open(sys.argv[1]) as json_file:
 23         inputlist = json.load(json_file)
 24         data=str(inputlist)
```
I then just wrote a vim macro to run through different parliament sizes. For reference, the macro was `:silent !python2 newarch.py data^M^A:w` - load up the "data" file, put the cursor on the seat number and tell vim to run the macro a hundred times. I'm sure there are better ways to do this, but that was a quick and dirty test using the tools that I'm used to.

**Pull request merged**
