### PR TITLE
Make the website more consistent, fix the US page

### LINKED ISSUE #121: US Diagram not functional
Currently attempts to generate a diagram using the [U.S. input form](https://parliamentdiagram.toolforge.org/USinputform.html) does not work.

### PR DESCRIPTION
**Pull request by Gouvernathor**
As I'm writing this, this version is deployed on [the beta environment](https://parliamentdiagram-beta.toolforge.org/archinputform.php) for testing purposes.
Fixes #121 and #146.
This aligns the layout of the US and Westminster pages with the main "arch" page. To do this, the html pages are transitioned to PHP pages, and the header with the passport photo is replaced with the heade of the arch page.
Redirects are placed where pages are removed, for compatibility, though this could preferably be done at the server level. That can be done in a future update.
This replaces the sample images with more up-to-date versions.
Also, adds myself to the footer 🙃 

**No change is brought to the newarch backend.** The resulting diagrams are exactly the same as before.
Two more updates, after this one, are about the python backend, the last one being the Revamp update.
They are the Gouv-clean-newarch and Gouv-clean-revamp branches. These three branches increment off each other.

I will merge this in two weeks (may 15th) if no feedback is provided.

### CODE REVIEW

**Comment by ljw1301** [comment]
Sorry to nag but still the Westminster diagram doesn't work in the beta version

**Comment by Gouvernathor** [comment]
Yep, there are other issues in python (due to py2->3 compatibility) that I'm working on addressing in another branch.

**Comment by ljw1301** [comment]
Oh okay, that makes sense

**Comment by Gouvernathor** [comment]
It's been two weeks, merging.

**Comment by ljw1301** [comment]
Hello I'm guessing it's meant to be this way but just in case, the diagrams don't save when uploaded by their links on websites as images for long

**Comment by ljw1301** [comment]
> Hello I'm guessing it's meant to be this way but just in case, the diagrams don't save when uploaded by their links on websites as images for long

And the crossbenches don't work

**Comment by Gouvernathor** [comment]
@ljw1301 

> it's meant to be this way

Yes it is, there's a cache expiration and you need to download your files, we'll eventually get in trouble if we start hoarding too many archives.

> And the crossbenches don't work

I'll look into that, but you can open a new issue describing the problem and how to reproduce it, as it's not really the topic of this issue.

**Comment by ljw1301** [comment]
Okay, thanks for letting me know

**Comment by Gouvernathor** [comment]
The westminster issue is #163, it's fixed in the Flask branch (it's not yet fixed on the Beta because that points to flask-oauth).

**Pull request merged**
