### PR TITLE
Fix revamp of seats positioning

### PR DESCRIPTION
**Pull request by Gouvernathor**
Fix #113.
The gitch in the number of seats is solved, the output is now similar to what my other code gives me, so if you don't like the result at least there's no bug distorting it.
I tried all numbers of seats until 4 rows, and randomly afterwards, I saw no difference but for the 1-seat newarch (but who cares ?).

Also it's now easier to test the main function, you can pass it the kind of dict you stored in the json file (just replace `false` with `False`).

### CODE REVIEW

**Comment by slashme** [comment]
Thanks, I'll take a look when I get home this afternoon!

**Comment by slashme** [comment]
@Gouvernathor - I don't know how to pass a parameter to the main function of this script when I'm running it. I've only ever run the script from the commandline, passing it arguments which get read using sys.argv, or by using cgi.fieldstorage when it's running as a web service. Please help :-D

**Comment by Gouvernathor** [comment]
In the very last part of the script, in the `if __main__`, call the main() function with a dict instead of nothing. Example :
```py
for k in range(300):
    inputlist = {
          "denser_rows": False,
          "parties": [
            {
              "name": "Party 1",
              "nb_seats": k,
              "color": "#95C241",
              "border_size": 0,
              "border_color": "#000000"
            }
          ]
        }
    main(inputlist=inputlist)
```
Put this in the if at the end of the file, maybe check the indentation, should generate the first 300 diagrams (actually 299 since range starts iterating at 0 and no seats is skipped).

**Comment by Gouvernathor** [comment]
You could also try and read the argv, but I find it a lot simpler to just edit and run the py file, including any version of the tests you want to run.

**Comment by Gouvernathor** [comment]
Hi ! Just checking in if you forgot about this. But no pressure ! ❤

**Comment by slashme** [comment]
Hello!

I've still got your emails in my inbox, reminding me to get around to it,
but I just haven't :-D

Absolutely on my to-do list as soon as my wild and crazy life settles
down...

David Richfield
+49 176 7266 3368

**Comment by slashme** [comment]
Hi @Gouvernathor , 

I've finally gotten back to real life, and I've started looking at your code again. I quickly tested it, and it seems that you removed the dense rows functionality. Was that intentional?

I'm going to start looking at the latest code by @Rade-Mathis now, will integrate yours once I'm done.

Thanks again for your help!!

**Comment by Gouvernathor** [comment]
It's partly intentional. Dense rows were added, if I'm not mistaken, because the formula for circles' width wasn't adapted to larger parliaments, so it added a second formula dedicated for that other case.
My version's formula makes it constant relative to the available room, so it short-circuits the need for the "dense rows" option.

**Comment by slashme** [comment]
OK, I just checked, and for example, a parliament with 5 seats really doesn't look good without the denser-rows option, either in my original code, or with this update, so I'd like to keep that option that gives a functionality something like that for smaller parliaments.

**Comment by Gouvernathor** [comment]
Point taken. Since my formula is supposed to be optimized, I'll try to understand how both ways currently work, and whether my math is wrong, or there's something mathematically inexact about the dense_rows option. If it is so, and I suppose it is, I'll see how I can translate it in my code.

**Comment by Rade-Mathis** [comment]
The idea of having "denser rows" as an option, is because going for one or another behavior shouldn't be a developer's decision, but a user's one.

On this kind of situation, the denser row (2nd image) is clearly better :
image
image

But in this situation
image
image
It's harder to say that one is better than another. What's worse? The sparseness of the 1st one? Or the thinness of the 2nd? By experience, different users won't agree on which one is the best. So we settled for an adaptable situation: Let any user do how they please.

**Comment by Gouvernathor** [comment]
I reimplemented a denser_rows option ! It works (math-wise) almost exactly like the original denser_rows option, a.k.a the old optimize_rows function, except it doesn't use magic numbers, and I think (and hope) it's more clear to understand and to maintain in the future.

I actually have a doubt about which is better, so I have 2 versions to propose. The one I committed, and the following in newarch.py line 99:
```diff
         radius = 1. / (4*nb_rows-2)
+        if dense_rows:
+            radius = .25 / nb_rows
```

You can test which one is better by testing the code I wrote [here](https://github.com/slashme/parliamentdiagram/pull/115#issuecomment-922524051) but with denser_rows being True.

**Comment by Gouvernathor** [comment]
Bonus : a display of what my math revamp yields (denser_rows unrelated, I could have drawn that figure sooner).
image
The constraints are written at the bottom. This image can be kept for posterity, if someone needs to explore my formulae.
By the way, `radius` (the radius of one seat, before it's diminished by 20% to make them not touch one another) is FH on the picture, so that's where the formula comes from and why to be accurate it needs to be a bit more complex than just some constant over `nb_rows`.

This math is not equivalent to what the no-revamp version yields : for some reason in the current version the innermost seats visibly go way more towards the center (see [this one](https://fr.wikipedia.org/wiki/XVIe_l%C3%A9gislature_de_la_Cinqui%C3%A8me_R%C3%A9publique_fran%C3%A7aise#/media/Fichier:France_XVIe_Assembl%C3%A9e_Nationale_2022.svg) for example).

**Pull request closed without merging**
