### PR TITLE
Newarch code cleaning

### PR DESCRIPTION
**Pull request by Rade-Mathis**
This is a rewriting of `newarch.py` file. This pull-request is only about reorganizing/cleaning the code :
* The outputted SVG is totally the same
* The algorithm used to generate it is also the same
* The only behavior modification is actually an added log (at the line 45)

The objective is to make the code more understandable, and hence, more easily modifiable.

Aesthetic choices have been made here:
* Use of camel_case identifiers (standard in python as far as I know)
* 80 column rule (some people consider it standard, but not everybody agrees on that)
* numpy style function documentation strings (because why not)

Tell me if any coding style choice is improper and should be replaced with another, I'll apply needed changes.

NB: I sent you a mail on your Gmail address, some comments in this commit are related to it.

### CODE REVIEW

**Comment by Rade-Mathis** [comment]
At the light of your email, I have to change a few things. It'll be back soon hopefully.

**Comment by slashme** [comment]
I've started looking at the work you've done so far, and I really like it!

Would you have a chance for a voice call? I've finished work and I have
time. Pretty much any VOIP system is fine: zoom, Google Chat, Telegram,
WhatsApp, etc. etc.

David Richfield
+49 176 7266 3368

**Comment by Rade-Mathis** [comment]
I don't really like phones calls. I will if needed, But I'd prefer text chat if possible.
I can make myself available tomorrow evening, from 6:40 PM up to whatever.

**Comment by slashme** [comment]
Text chat is fine! Let's try 19:00. What platform do you prefer? IRC,
slack, Google ... ?

RadeMathis ***@***.***> schrieb am Mi., 28. Apr. 2021, 00:05:

**Comment by Rade-Mathis** [comment]
I'll be able to vocal. You can join me here if it suits you: [https://discord.gg/ZTtq3J8P](https://discord.gg/ZTtq3J8P)

**Comment by slashme** [comment]
Great, will be online in about 10 minutes.

RadeMathis ***@***.***> schrieb am Mi., 28. Apr. 2021, 18:47:

**Pull request closed without merging**
