### PR TITLE
Better small parliament

### PR DESCRIPTION
**Pull request by Rade-Mathis**
## What does that do?

In diagram that are "small" (ie: near the lowest bound of their tier, in the TOTAL list), refuses to fill the innermost rows, in order to have denser populated outermost rows

## Issues implemented

#4 and #39 

## Tests

Here be few SVGs generated by this version : [examples-smalldiagram-svg.zip](https://github.com/slashme/parliamentdiagram/files/6447325/examples-smalldiagram-svg.zip)

## Drawbacks?

I think some graph look weird because they are thin (see my tests' example `34.svg`). But I also think this is worth it, considering how prettier became diagrams such as `5.svg` or `9.svg`

## Requirements

This is a request to pull the branch `Rade-Mathis:better-small-parliament` which is based on the top of `Rade-Mathis:newarch-code-cleaning`. The latest one is pull-requested by #96.

I don't know how GitHub's pull-requests work. So I'll advise to treat #96 before this one. If something wrong or weird happens when trying to pull this one, I'll make a new one after #96 has been pulled.

### CODE REVIEW

**Comment by Rade-Mathis** [comment]
Note line 200 : `round(max_spot_in_row)`. I assumed rounding the value was the right thing to do. But empirical tests seems to work, hence I pushed it.

**Comment by slashme** [comment]
I'm looking at this and it's a great improvement in most cases, but when the diagram has the full number of rows, this new version fills the outermost row more than the others. I'm investigating why before making it go live.

**Comment by Rade-Mathis** [comment]
Weird things happen at line 200.

I am using a `round()` to determine how many spot a row can contain. This is not what your algorithm was doing, yours what doing a ìnt()` (ie: a floor). This works in most cases, except for a 4 spots diagram, where `pi / (2 * asin(2.0 / (3.0 * 1 + 4.0 * 1 - 2.0)))` is ~3.8, hence lower than 4.

I see 2 solutions so far:
- Change `TOTALS[0]` to `3` (rather than `4`)
- Do the math to find a better formula

Do you have a particular opinion about that?

**Comment by slashme** [comment]
If changing the threshold for a one-row diagram fixes the problem, I would go for your first solution!

**Comment by Rade-Mathis** [comment]
I'm on it so

**Comment by Rade-Mathis** [comment]
Modification done. So it's open to be pulled again.

Test cases : [smallparli-svg-examples.zip](https://github.com/slashme/parliamentdiagram/files/6494145/smallparli-svg-examples.zip)

Note `4.svg`, spanning on the outer row of a 2 row sized diagram. Kinda weird but working.

**Comment by Rade-Mathis** [comment]
Side note: This pull-request embed a small modification about how logs are done, it will be easier this way.

**Comment by slashme** [comment]
Thank you! I'm learning so much from you!

**Comment by Rade-Mathis** [comment]
Do not hesitate if you have any question.

**Pull request merged**
