### PR TITLE
Make parties sortable

### PR DESCRIPTION
**Pull request by Gouvernathor**

### CODE REVIEW

**Comment by Gouvernathor** [comment]
@slashme @yee-bit @smashter the solution is available on [the Beta](https://parliamentdiagram-beta.toolforge.org/archinputform), feel free to test it and to tell me what you think of it.
I'll merge it in a week or less otherwise (other stuff is waiting).

**Comment by yee-bit** [comment]
Thanks, for the fix mate, I'm not seeing a way to reorder it however, still functions the same on my end. Might take a minute to update for me, but just thought I'd give you a heads up.

**Comment by Gouvernathor** [comment]
Yup, I mistakenly switched it back.
You'll need to flush the cache (Ctrl+F5) for it to work properly, for some reason.

**Comment by yee-bit** [comment]
Fixed, works like butter. Thanks for this feature :)

**Pull request merged**
